server:
  port: 8080
spring:
  devtools:
    restart:
      enabled: true # 소스파일에 변화가 있을 때 자동으로 서버 재 시작 설정
    livereload:
      enabled: true # 정적 리소스에 변화가 있을 때 바로 반영한다.
  output:
    ansi:
     enabled: always
  profiles:
    include: oracle # include application-oracle.yml (오라클 접속정보 숨김)

mybatis:
  mapper-locations: classpath:mapper/**/*.xml # mapper.xml 위치 명시
  configuration:
    map-underscore-to-camel-case: true # model 프로퍼티 camel case 설정
  type-aliases-package: com.kh.zipplanet  # 매핑할 모델의 패키지 경로 (mybatis 매핑 type을 짧게 쓰기 위한 설정)

logging:
  level:
    com:
      azurealstn:
        codespringweb:
          mapper: TRACE # mapper 로그레벨 설정

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true

  mail:
    host: smtp.naver.com  #메일 설정에서 smtp 설정 필요
    port: 465
    username: zip-planet@naver.com
    password: zip!@8426
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com
      mail.smtp.starttls.enable: true